apiVersion: v1
entries:
  sinfonia-apps:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2024-02-23T15:54:20.364835-05:00"
    description: A Helm chart for Kubernetes
    digest: 756a67fef090bca495a0dc0e621567942e78499aa9763deb86324fed5a04da5d
    name: sinfonia-apps
    type: application
    urls:
    - file://charts/sinfonia-apps-0.1.0.tgz
    version: 0.1.0
generated: "2024-02-23T15:54:20.363133-05:00"
